from dotenv import load_dotenv

from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq


load_dotenv()


llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0
)


faithfulness_prompt = ChatPromptTemplate.from_template(
    """
You are evaluating the faithfulness of an answer generated by a
Retrieval-Augmented Generation (RAG) system.

Determine whether the generated answer is fully supported by the
provided context.

Context:
{context}

Generated Answer:
{answer}

Rules:

1. Evaluate every factual claim in the generated answer.
2. A claim is supported only when the context provides evidence
   for that claim.
3. Do not use outside knowledge.
4. Ignore differences in wording.
5. If every factual claim is supported, return:

FAITHFUL

6. If any factual claim is unsupported or contradicts the context,
   return:

NOT_FAITHFUL

Return ONLY one of:

FAITHFUL
NOT_FAITHFUL
"""
)


def evaluate_faithfulness(question,context, answer):

    messages = faithfulness_prompt.invoke(
        {
            "context": context,
            "answer": answer
        }
    )

    response = llm.invoke(messages)

    result = response.content.strip().upper()

    if "NOT_FAITHFUL" in result:
        return "NOT_FAITHFUL"

    if "FAITHFUL" in result:
        return "FAITHFUL"

    return "UNKNOWN"