import os

from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate


load_dotenv()


llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0
)


evaluation_prompt = ChatPromptTemplate.from_template(
    """
You are evaluating the correctness of an answer generated by a
RAG document question-answering system.

Evaluate the generated answer against the expected answer.

Question:
{question}

Expected Answer:
{expected_answer}

Generated Answer:
{generated_answer}

Determine whether the generated answer is semantically correct.

Consider:

1. Does it answer the question?
2. Does it contain the important facts from the expected answer?
3. Does it contradict the expected answer?
4. Are there unsupported or incorrect claims?

Return ONLY one of these:

CORRECT
INCORRECT
"""
)


def evaluate_answer(
    question,
    expected_answer,
    generated_answer
):
    messages = evaluation_prompt.invoke(
        {
            "question": question,
            "expected_answer": expected_answer,
            "generated_answer": generated_answer
        }
    )

    response = llm.invoke(messages)

    result = response.content.strip().upper()

    return result